//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_Policy_Endorsement_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nominee
    {
        public int NomineeId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string NomineeName { get; set; }
        public string Relation { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
